---
- name: set timezone
  timezone:
    name: Asia/Tokyo

- name: get language-pack packages
  apt: name={{ item }} state=present
  with_items:
    - language-pack-ja-base
    - language-pack-ja

- name: update-locale
  locale_gen:
    name: ja_JP.UTF-8
    state: present
